export const festivalId = "outside-lands-2026";

export const seedArtists = [
  {
    jambaseId: "artist-charli-xcx",
    name: "Charli XCX",
    image: "/window.svg",
    genres: ["hyperpop", "electropop"],
    hometown: "Cambridge, England",
    bio: "Glossy pop chaos with festival-sized hooks.",
    topTrack: "https://www.youtube.com/watch?v=XXX",
    jambaseUrl: "https://www.jambase.com/artist/charli-xcx",
  },
  {
    jambaseId: "artist-rufus-du-sol",
    name: "RÜFÜS DU SOL",
    image: "/globe.svg",
    genres: ["indie electronic", "dance"],
    hometown: "Sydney, Australia",
    bio: "Balearic build-ups and huge closing sets.",
    topTrack: "https://www.youtube.com/watch?v=XXX",
    jambaseUrl: "https://www.jambase.com/artist/rufus-du-sol",
  },
  {
    jambaseId: "artist-the-strokes",
    name: "The Strokes",
    image: "/file.svg",
    genres: ["indie rock", "garage rock"],
    hometown: "New York, New York",
    bio: "A festival headliner with sharp edges and zero wasted motion.",
    topTrack: "https://www.youtube.com/watch?v=XXX",
    jambaseUrl: "https://www.jambase.com/artist/the-strokes",
  },
  {
    jambaseId: "artist-muna",
    name: "MUNA",
    image: "/vercel.svg",
    genres: ["indie pop", "dance-pop"],
    hometown: "Los Angeles, California",
    bio: "Big feelings, bigger chorus lifts.",
    topTrack: "https://www.youtube.com/watch?v=XXX",
    jambaseUrl: "https://www.jambase.com/artist/muna",
  },
  {
    jambaseId: "artist-doechii",
    name: "Doechii",
    image: "/window.svg",
    genres: ["hip-hop", "rap"],
    hometown: "Tampa, Florida",
    bio: "Fast-switching, charismatic, and built for a crowd.",
    topTrack: "https://www.youtube.com/watch?v=XXX",
    jambaseUrl: "https://www.jambase.com/artist/doechii",
  },
  {
    jambaseId: "artist-faye-webster",
    name: "Faye Webster",
    image: "/globe.svg",
    genres: ["indie folk", "alt-country"],
    hometown: "Atlanta, Georgia",
    bio: "Soft-focus songs that land harder than they look.",
    topTrack: "https://www.youtube.com/watch?v=XXX",
    jambaseUrl: "https://www.jambase.com/artist/faye-webster",
  },
  {
    jambaseId: "artist-jamie-xx",
    name: "Jamie xx",
    image: "/file.svg",
    genres: ["electronic", "dance"],
    hometown: "London, England",
    bio: "A night set that keeps the whole field moving.",
    topTrack: "https://www.youtube.com/watch?v=XXX",
    jambaseUrl: "https://www.jambase.com/artist/jamie-xx",
  },
  {
    jambaseId: "artist-vampire-weekend",
    name: "Vampire Weekend",
    image: "/vercel.svg",
    genres: ["indie rock", "jam"],
    hometown: "New York, New York",
    bio: "Bright, precise, and somehow still loose enough for sunset.",
    topTrack: "https://www.youtube.com/watch?v=XXX",
    jambaseUrl: "https://www.jambase.com/artist/vampire-weekend",
  },
] as const;

export const seedVenues = [
  {
    jambaseId: "venue-golden-gate-park",
    name: "Golden Gate Park",
    city: "San Francisco",
    region: "CA",
    latitude: 37.7694,
    longitude: -122.4862,
    image: "/window.svg",
    description: "Outside Lands turns Golden Gate Park into a multi-stage live music city.",
    website: "https://www.sfoutsidelands.com/",
    jambaseUrl: "https://www.jambase.com/venue/golden-gate-park",
  },
  {
    jambaseId: "venue-sutro-stage",
    name: "Sutro Stage",
    city: "San Francisco",
    region: "CA",
    latitude: 37.7679,
    longitude: -122.4586,
    image: "/globe.svg",
    description: "A wooded Outside Lands stage known for close crowds and discovery sets.",
    website: "https://www.sfoutsidelands.com/",
    jambaseUrl: "https://www.jambase.com/venue/sutro-stage",
  },
  {
    jambaseId: "venue-lands-end",
    name: "Lands End",
    city: "San Francisco",
    region: "CA",
    latitude: 37.7804,
    longitude: -122.5139,
    image: "/file.svg",
    description: "The festival's largest field and home to its biggest headline moments.",
    website: "https://www.sfoutsidelands.com/",
    jambaseUrl: "https://www.jambase.com/venue/lands-end",
  },
] as const;

export const seedShows = [
  {
    jambaseId: "show-charli-xcx-2026-08-07",
    title: "Charli XCX",
    date: "2026-08-07",
    day: "Friday",
    time: "8:20 PM",
    memoryPrompt: "What was the crowd moment you will remember?",
    venueJambaseId: "venue-golden-gate-park",
    venueName: "Golden Gate Park",
    city: "San Francisco",
    image: "/window.svg",
    festivalId,
    stage: "Twin Peaks",
    isHeadliner: true,
    artistJambaseIds: ["artist-charli-xcx"],
    artistNames: ["Charli XCX"],
    jambaseUrl: "https://www.jambase.com/show/charli-xcx-2026-08-07",
    ticketUrl: "https://www.sfoutsidelands.com/tickets/",
  },
  {
    jambaseId: "show-vampire-weekend-2026-08-07",
    title: "Vampire Weekend",
    date: "2026-08-07",
    day: "Friday",
    time: "6:30 PM",
    memoryPrompt: "Which song turned the field into a singalong?",
    venueJambaseId: "venue-lands-end",
    venueName: "Lands End",
    city: "San Francisco",
    image: "/globe.svg",
    festivalId,
    stage: "Main Stage",
    isHeadliner: false,
    artistJambaseIds: ["artist-vampire-weekend"],
    artistNames: ["Vampire Weekend"],
    jambaseUrl: "https://www.jambase.com/show/vampire-weekend-2026-08-07",
    ticketUrl: "https://www.sfoutsidelands.com/tickets/",
  },
  {
    jambaseId: "show-rufus-du-sol-2026-08-08",
    title: "RÜFÜS DU SOL",
    date: "2026-08-08",
    day: "Saturday",
    time: "8:10 PM",
    memoryPrompt: "Which drop made the field feel weightless?",
    venueJambaseId: "venue-golden-gate-park",
    venueName: "Golden Gate Park",
    city: "San Francisco",
    image: "/file.svg",
    festivalId,
    stage: "Main Stage",
    isHeadliner: true,
    artistJambaseIds: ["artist-rufus-du-sol"],
    artistNames: ["RÜFÜS DU SOL"],
    jambaseUrl: "https://www.jambase.com/show/rufus-du-sol-2026-08-08",
    ticketUrl: "https://www.sfoutsidelands.com/tickets/",
  },
  {
    jambaseId: "show-doechii-2026-08-08",
    title: "Doechii",
    date: "2026-08-08",
    day: "Saturday",
    time: "5:45 PM",
    memoryPrompt: "Which lyric got the group chat going?",
    venueJambaseId: "venue-sutro-stage",
    venueName: "Sutro Stage",
    city: "San Francisco",
    image: "/vercel.svg",
    festivalId,
    stage: "Sutro",
    isHeadliner: false,
    artistJambaseIds: ["artist-doechii"],
    artistNames: ["Doechii"],
    jambaseUrl: "https://www.jambase.com/show/doechii-2026-08-08",
    ticketUrl: "https://www.sfoutsidelands.com/tickets/",
  },
  {
    jambaseId: "show-the-strokes-2026-08-09",
    title: "The Strokes",
    date: "2026-08-09",
    day: "Sunday",
    time: "8:30 PM",
    memoryPrompt: "Which song turned strangers into backup singers?",
    venueJambaseId: "venue-golden-gate-park",
    venueName: "Golden Gate Park",
    city: "San Francisco",
    image: "/window.svg",
    festivalId,
    stage: "Main Stage",
    isHeadliner: true,
    artistJambaseIds: ["artist-the-strokes"],
    artistNames: ["The Strokes"],
    jambaseUrl: "https://www.jambase.com/show/the-strokes-2026-08-09",
    ticketUrl: "https://www.sfoutsidelands.com/tickets/",
  },
  {
    jambaseId: "show-muna-faye-webster-2026-08-09",
    title: "MUNA + Faye Webster",
    date: "2026-08-09",
    day: "Sunday",
    time: "6:00 PM",
    memoryPrompt: "Which chorus or quiet moment stayed with you?",
    venueJambaseId: "venue-lands-end",
    venueName: "Lands End",
    city: "San Francisco",
    image: "/globe.svg",
    festivalId,
    stage: "Lands End",
    isHeadliner: false,
    artistJambaseIds: ["artist-muna", "artist-faye-webster"],
    artistNames: ["MUNA", "Faye Webster"],
    jambaseUrl: "https://www.jambase.com/show/muna-faye-webster-2026-08-09",
    ticketUrl: "https://www.sfoutsidelands.com/tickets/",
  },
  {
    jambaseId: "show-jamie-xx-2026-08-09",
    title: "Jamie xx",
    date: "2026-08-09",
    day: "Sunday",
    time: "9:00 PM",
    memoryPrompt: "What was the moment the whole field started moving?",
    venueJambaseId: "venue-sutro-stage",
    venueName: "Sutro Stage",
    city: "San Francisco",
    image: "/file.svg",
    festivalId,
    stage: "Sutro",
    isHeadliner: true,
    artistJambaseIds: ["artist-jamie-xx"],
    artistNames: ["Jamie xx"],
    jambaseUrl: "https://www.jambase.com/show/jamie-xx-2026-08-09",
    ticketUrl: "https://www.sfoutsidelands.com/tickets/",
  },
] as const;

export const seedUsers = [
  { handle: "tinsley", avatarColor: "#20d6aa", isFake: false },
  { handle: "maya", avatarColor: "#ff3b0e", isFake: true },
  { handle: "leo", avatarColor: "#8b5cf6", isFake: true },
  { handle: "sam", avatarColor: "#0ea5e9", isFake: true },
  { handle: "ava", avatarColor: "#22c55e", isFake: true },
  { handle: "jordan", avatarColor: "#f59e0b", isFake: true },
] as const;

export const seedLogs = [
  {
    userHandle: "tinsley",
    showJambaseId: "show-charli-xcx-2026-08-07",
    rating: 5,
    vibes: ["transcendent", "sweaty"],
    note: "The whole hill screamed every word. Instant favorite.",
    createdAt: 1786100200000,
  },
  {
    userHandle: "tinsley",
    showJambaseId: "show-doechii-2026-08-08",
    rating: 4.5,
    vibes: ["sound was insane"],
    note: "Best crowd control of the weekend, and it was not close.",
    createdAt: 1786188200000,
  },
  {
    userHandle: "tinsley",
    showJambaseId: "show-rufus-du-sol-2026-08-08",
    rating: 4,
    vibes: ["sunset set"],
    note: "Fog arrived at exactly the right moment.",
    createdAt: 1786186400000,
  },
  {
    userHandle: "maya",
    showJambaseId: "show-charli-xcx-2026-08-07",
    rating: 5,
    vibes: ["transcendent", "sunset set"],
    note: "She had the whole field yelling every hook.",
    createdAt: 1786100400000,
  },
  {
    userHandle: "maya",
    showJambaseId: "show-rufus-du-sol-2026-08-08",
    rating: 4.5,
    vibes: ["sound was insane", "all-nighter"],
    note: "Huge ending, no notes.",
    createdAt: 1786186800000,
  },
  {
    userHandle: "maya",
    showJambaseId: "show-the-strokes-2026-08-09",
    rating: 4,
    vibes: ["too packed"],
    note: "Crowd was intense but the set still hit.",
    createdAt: 1786273200000,
  },
  {
    userHandle: "leo",
    showJambaseId: "show-rufus-du-sol-2026-08-08",
    rating: 5,
    vibes: ["sound was insane", "sunset set"],
    note: "Exactly the kind of night set I wanted.",
    createdAt: 1786187400000,
  },
  {
    userHandle: "leo",
    showJambaseId: "show-jamie-xx-2026-08-09",
    rating: 4.5,
    vibes: ["all-nighter", "surprise guest"],
    note: "Kept getting better every minute.",
    createdAt: 1786275000000,
  },
  {
    userHandle: "sam",
    showJambaseId: "show-the-strokes-2026-08-09",
    rating: 4.5,
    vibes: ["transcendent"],
    note: "Classic set, zero filler.",
    createdAt: 1786273800000,
  },
  {
    userHandle: "sam",
    showJambaseId: "show-muna-faye-webster-2026-08-09",
    rating: 4,
    vibes: ["sunset set"],
    note: "Two very different moods, both great.",
    createdAt: 1786275600000,
  },
  {
    userHandle: "ava",
    showJambaseId: "show-charli-xcx-2026-08-07",
    rating: 5,
    vibes: ["transcendent", "surprise guest"],
    note: "A festival highlight for sure.",
    createdAt: 1786101000000,
  },
  {
    userHandle: "ava",
    showJambaseId: "show-doechii-2026-08-08",
    rating: 4.5,
    vibes: ["sound was insane"],
    note: "Big energy from start to finish.",
    createdAt: 1786188600000,
  },
  {
    userHandle: "jordan",
    showJambaseId: "show-jamie-xx-2026-08-09",
    rating: 5,
    vibes: ["all-nighter"],
    note: "The perfect way to close the festival.",
    createdAt: 1786276200000,
  },
] as const;
